/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delfinen.presentation;

import delfinen.data.Betaling;
import delfinen.data.DataAccessorFile;
import delfinen.data.Disciplin;
import delfinen.data.Konkurrencesvømmer;
import delfinen.data.Medlem;
import delfinen.logic.BetalingCalculator;
import delfinen.logic.Controller;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Talha Noory
 */
public class Kontingent extends javax.swing.JFrame {

    private Controller c;

    /**
     * Creates new form Kontingent
     */
    public Kontingent() {
        initComponents();
        DataAccessorFile dao = new DataAccessorFile();
        BetalingCalculator bc = new BetalingCalculator();
        c = new Controller(dao, bc);
        c.getMedlemmer();
        visAlleBetalinger();
    }

    public DefaultTableModel createTable(JTable t) {
        DefaultTableModel model = (DefaultTableModel) t.getModel();
        int rowCount = model.getRowCount();
        int ColumnCount = model.getColumnCount();
        t.isCellEditable(rowCount, ColumnCount - 1);
        return model;
    }

    public void visMedlemmerRestance() {

        DefaultTableModel model = createTable(this.jTable1);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        int tempCPR = 0;
        for (Medlem m : c.getMedlemmerIRestance()) {
            Object rowData[] = new Object[4];
            rowData[0] = m.getName();
            rowData[1] = m.getCprnr();
            rowData[2] = m.getMail();
            rowData[3] = c.getBetalingByYear(m, Calendar.getInstance().get(Calendar.YEAR)).getBetalingssum();

            model.addRow(rowData);

        }
    }
    public void visAlleBetalinger(){
       
        DefaultTableModel model = createTable(this.JBetaling);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        int tempCPR = 0;
        for (Betaling b : c.getAlleBetalinger()) {
            Object rowData[] = new Object[6];
            rowData[0] = b.getName();
            rowData[1] = b.getCPR();
            rowData[2] = b.getBetalingsyear();
            rowData[3] = b.isHasPaid();
            rowData[4] = b.getBetalingssum();
            rowData[5] = b.getId();
            

            model.addRow(rowData);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonIndkomst = new javax.swing.JButton();
        jYear = new javax.swing.JTextField();
        Jforventet = new javax.swing.JTextField();
        jButtonHovedemenu = new javax.swing.JButton();
        jButtonRestance = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JOpret = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        JBetaling = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jTextField1.setText("jTextField1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonIndkomst.setText("Se indkomst");
        jButtonIndkomst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndkomstActionPerformed(evt);
            }
        });

        jYear.setText("Indtast årstal");

        Jforventet.setEditable(false);
        Jforventet.setText("Forventet indkomst fra år");

        jButtonHovedemenu.setText("Hovedemenu");
        jButtonHovedemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHovedemenuActionPerformed(evt);
            }
        });

        jButtonRestance.setText("Se medlemmer i restance");
        jButtonRestance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestanceActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\nPassivt medlemskab:\t500 kr. årligt,\n\nAlder\n\n0 - 17 :\t\t1000 kr. årligt,\n\n18 - 60 :\t\t1600 kr. årligt,\n\n60 eller over :\t\t1200 kr. årligt");
        jScrollPane1.setViewportView(jTextArea1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Navn", "CPR", "Email", "Beløb"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        JOpret.setText("Ret Betaling");
        JOpret.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOpretActionPerformed(evt);
            }
        });

        JBetaling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Navn", "CPR", "Betalingsår", "Betalt/Ikke betalt", "Beløb", "ID"
            }
        ));
        jScrollPane4.setViewportView(JBetaling);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRestance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jYear)
                                    .addComponent(jButtonIndkomst, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(Jforventet, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JOpret, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(194, 194, 194)
                                .addComponent(jButtonHovedemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jButtonRestance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Jforventet, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jButtonIndkomst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHovedemenu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JOpret, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIndkomstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndkomstActionPerformed
        try {
            int indkomst = c.getForventetIndkomstFraKontingenter(Integer.parseInt(this.jYear.getText()));

            this.Jforventet.setText("" + indkomst);
        } catch (Exception ex) {

        }
    }//GEN-LAST:event_jButtonIndkomstActionPerformed

    private void jButtonHovedemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHovedemenuActionPerformed
        this.dispose();
        Hovedemenu hm = new Hovedemenu();
        hm.setVisible(true);
    }//GEN-LAST:event_jButtonHovedemenuActionPerformed

    private void jButtonRestanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestanceActionPerformed
        visMedlemmerRestance();
    }//GEN-LAST:event_jButtonRestanceActionPerformed

    private void JOpretActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOpretActionPerformed
         
        
           

           Medlem tempMedlem = c.getMedlemPåCprnr(Integer.parseInt(this.JBetaling.getValueAt(this.JBetaling.getSelectedRow(), 1).toString()));
            this.jLabel1.setText("CPR: " + tempMedlem.getCprnr());
            this.jLabel2.setText("Navn: " + tempMedlem.getName());
            this.jLabel3.setText("ID: " + this.JBetaling.getValueAt(this.JBetaling.getSelectedRow(), 5).toString());
            this.jTextField1.setText("");
            boolean isPaid = false;

            Object[] message = {
                "", jLabel1,
                "", jLabel2,
                "", jLabel3,
                "Betalt eller ikke betalt", jTextField1

            };
            
            
            int option = JOptionPane.showConfirmDialog(null, message, "Opret Betaling", JOptionPane.OK_CANCEL_OPTION);
            if (option == JOptionPane.OK_OPTION) {
                if(this.jTextField1.getText().toLowerCase().equals("betalt")){
                    isPaid = true;
                    
                }else{
                    isPaid = false;
                }
                //jeg har lavet en ny attribut til betaling der er en boolean.
                //hvis de betaler 0, altså ikke betaler skal den sættes til false, ellers til true
                try {
                    for(Betaling b : c.getAlleBetalinger()){
                        if(b.getId() == Integer.parseInt(this.JBetaling.getValueAt(this.JBetaling.getSelectedRow(), 5).toString())){
                            c.redigerBetaling(b, isPaid);
                            System.out.println("her");
                        }
                    }
                

            }catch (Exception ex) {
        } 

        }
            visAlleBetalinger();
    }//GEN-LAST:event_JOpretActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kontingent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kontingent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kontingent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kontingent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kontingent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JBetaling;
    private javax.swing.JButton JOpret;
    private javax.swing.JTextField Jforventet;
    private javax.swing.JButton jButtonHovedemenu;
    private javax.swing.JButton jButtonIndkomst;
    private javax.swing.JButton jButtonRestance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jYear;
    // End of variables declaration//GEN-END:variables
}
