/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package delfinen.presentation;

import delfinen.data.Betaling;
import delfinen.data.DataAccessorFile;
import delfinen.data.Disciplin;
import delfinen.data.Konkurrencesvømmer;
import delfinen.data.Medlem;
import delfinen.data.Resultat;
import delfinen.logic.BetalingCalculator;
import delfinen.logic.Controller;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Talha Noory
 */
public class SvømmeResultater extends javax.swing.JFrame {
    private Controller c;
    /**
     * Creates new form SvømmeResultater
     */
    public SvømmeResultater() {
        initComponents();
        DataAccessorFile dao = new DataAccessorFile();
        BetalingCalculator bc = new BetalingCalculator();
        c = new Controller(dao, bc);
        c.getMedlemmer();
        this.setTitle("Svømmeresultater");
    }
        public DefaultTableModel createTable(JTable t) {
        DefaultTableModel model = (DefaultTableModel) t.getModel();
        int rowCount = model.getRowCount();
        int ColumnCount = model.getColumnCount();
        t.isCellEditable(rowCount, ColumnCount - 1);
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButtonRegistrerSvømmeresultat = new javax.swing.JButton();
        jButtonHovedemenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTop5 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        JResultater = new javax.swing.JTable();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Se Crawlresultater");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Se brystsvømningsresultater");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Se rygcrawlresultater");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Se butterflyresultater");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Se top 5 i rygcrawl");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Se top 5 i crawl");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Se top 5 i brystsvømning");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Se top 5 i butterfly");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButtonRegistrerSvømmeresultat.setText("Coach View");
        jButtonRegistrerSvømmeresultat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrerSvømmeresultatActionPerformed(evt);
            }
        });

        jButtonHovedemenu.setText("Hovedemenu");
        jButtonHovedemenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHovedemenuActionPerformed(evt);
            }
        });

        JTop5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Navn", "Disciplin", "Placering", "Tid"
            }
        ));
        jScrollPane1.setViewportView(JTop5);

        JResultater.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Navn", "Disciplin", "Placering", "Tid"
            }
        ));
        jScrollPane4.setViewportView(JResultater);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonRegistrerSvømmeresultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonHovedemenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(19, 19, 19)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonHovedemenu, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(jButtonRegistrerSvømmeresultat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model = createTable(this.JResultater);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getDisciplinResultater(Disciplin.CRAWL)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        DefaultTableModel model = createTable(this.JResultater);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getDisciplinResultater(Disciplin.RYGCRAWL)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        DefaultTableModel model = createTable(this.JResultater);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getDisciplinResultater(Disciplin.BUTTERFLY)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        DefaultTableModel model = createTable(this.JResultater);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getDisciplinResultater(Disciplin.BRYSTSVØMNING)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       
        DefaultTableModel model = createTable(this.JTop5);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getTop5(Disciplin.CRAWL)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
             
        DefaultTableModel model = createTable(this.JTop5);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getTop5(Disciplin.RYGCRAWL)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
                   
        DefaultTableModel model = createTable(this.JTop5);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getTop5(Disciplin.BUTTERFLY)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                    
        DefaultTableModel model = createTable(this.JTop5);
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for (Resultat t : c.getTop5(Disciplin.BRYSTSVØMNING)) {
                Object rowData[] = new Object[4];
                rowData[0] = t.getName();
                rowData[1] = t.getDisciplin();
                rowData[2] = t.getPlacement();
                rowData[3] = c.timeFormatter(t.getTimeInSeconds());


                
                model.addRow(rowData);

            

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonHovedemenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHovedemenuActionPerformed
        this.dispose();
        Hovedemenu hm = new Hovedemenu();
        hm.setVisible(true);
    }//GEN-LAST:event_jButtonHovedemenuActionPerformed

    private void jButtonRegistrerSvømmeresultatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrerSvømmeresultatActionPerformed
        this.dispose();
        CoachView cw = new CoachView();
        cw.setVisible(true);
    }//GEN-LAST:event_jButtonRegistrerSvømmeresultatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SvømmeResultater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SvømmeResultater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SvømmeResultater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SvømmeResultater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SvømmeResultater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JResultater;
    private javax.swing.JTable JTop5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonHovedemenu;
    private javax.swing.JButton jButtonRegistrerSvømmeresultat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
